version: '3.7'

services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - NODE_FUNCTION_ALLOW_EXTERNAL=cheerio,pptxgenjs
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data: